### ISSUE TITLE
Improve anti cheat.

### ISSUE THREAD

**Issue by devendrapoonia** [FarisHijazi/10FastFingers_BotAntiAntiCheat#2]
Add a feature that deliberately incorrect some words while typing, so it will make look like realistic.
Rates can be random every time like - 
(min words-max words)
2-6
1-3
3-5
2-7
Thank You.

**Comment by FarisHijazi** [comment]
https://github.com/FarisHijazi/10FastFingers_BotAntiAntiCheat/blob/6d78e0d0d7e6b9ec4dd4f95105f16217c29c2b6d/10fastfingers_bot_antianticheat.user.js#L129

I added an `errorRate` variable that you can change in the code.
this should have the desired affects, I tested it once and it seemed to do the job
